### PR TITLE
Add filler macros and script

### PR DESCRIPTION
**Pull request by dnltz**
Add filler macros from Daniel Arevalos and Krzysztof Herman. Also add a Python script to automatically fill a layout and save it.

The following example will fill all layers and generates a DRC clean layout file afterwards.
```
klayout -n sg13g2 -zz -r /home/daniel/work/elements/i2c-gpio-expander/pdks/IHP-Open-PDK/ihp-sg13g2/libs.tech/klayout//tech/scripts/filler.py \
	-rd output_file=/home/daniel/work/elements/i2c-gpio-expander/tools/OpenROAD-flow-scripts/flow/results/ihp-sg13g2/SG13G2Top/base/6_final.gds \
	/home/daniel/work/elements/i2c-gpio-expander/tools/OpenROAD-flow-scripts/flow/results/ihp-sg13g2/SG13G2Top/base/6_final.gds
```

### CODE REVIEW

**Comment by KrzysztofHerman** [comment]
@dnltz thank you for the contribution. First of all we should adjust the operation of the density analyzer, which should calculate total coverage of a particular layer and densities in the square of 800x800 um window. You could take a look at https://www.klayout.de/forum/discussion/167/density-for-a-layer link. 
Additionally a more fine grain cells can be used in order to hit the desired density evaluating in the loop a result of previous iteration. Thus one can be sure that the DRC rules for metal fill and metal density are met.

**Comment by dnltz** [comment]
@KrzysztofHerman yes, I will check the layout rules for 800x800 windows. What's the ideal density? Just in the middle of min/max?

**Comment by KrzysztofHerman** [comment]
@dnltz I would work for the middle value at the beginning.  Let's see how it converges.

**Comment by sergeiandreyev** [comment]
closing this as we have a new one #229

**Pull request closed without merging**
