### PR TITLE
PyCell for Klayout

### PR DESCRIPTION
**Pull request by ThomasZecha**
-added ptap1 PyCell

### CODE REVIEW

**Review by KrzysztofHerman — COMMENTED** [review]
Thank you Thomas for the contribution. After reviewing this PR I have the following observations:

- the `!sub` text is upside down
- the orign of the cell would be better to place it at left bottom corner
- the parameters R, Area, Perimeter does not update.

**Comment by ThomasZecha** [comment]
@KrzysztofHerman: I assume your comments are dedicated to @sergeiandreyev ?

**Comment by KrzysztofHerman** [comment]
> @KrzysztofHerman: I assume your comments are dedicated to @sergeiandreyev ?

The comments are dedicated to the developer of the `ptap1` pycell, whoever he/she is.  I have mentioned you since you are the author of this PR.

**Comment by sergeiandreyev** [comment]
> @KrzysztofHerman: I assume your comments are dedicated to @sergeiandreyev ?

yes, I agree that the callbacks are not working, while the other staff:
- `sub!` is ok on my side
image
- the origin is in line with implementation in commercial PDK (we should discuss this internally)

btw, this cell is still in progress, I did not expect Thomas to push it :)

**Comment by sergeiandreyev** [comment]
@ThomasZecha, did you update the `pycell4klayout` submodule reference version in the OpenPDK?
It still shows me (`git submodule`):
```
 9a6e7c9d404f9f4334513a24788aa8454918d400 ihp-sg13g2/libs.tech/digital (heads/master)
+6dc3d13d8a82eb82e16858c34cb37f8f06af5e1a ihp-sg13g2/libs.tech/klayout/python/pycell4klayout-api (6dc3d13)
 6ddd5783365718c41eb69bce4428358ace4d1fa2 ihp-sg13g2/libs.tech/klayout/python/pypreprocessor (heads/master)
 ```
 Maybe I'm doing smth wrong..

**Comment by ThomasZecha** [comment]
Yes, I have, see
https://github.com/IHP-GmbH/pycell4klayout-api/commits/main/ shows0 commit _fa73bbf_

**Pull request merged**
