### PR TITLE
libs.tech: Klayout: tech: Add layer map

### PR DESCRIPTION
**Pull request by dnltz**
OpenROAD requires the sg13g2.map file to correctly place each layer. Fix this here to not overwrite manually changes in OpenROAD-Flow-Scripts.

### CODE REVIEW

**Comment by sergeiandreyev** [comment]
Hi @dnltz, is it possible to just put the `.map` file to this repo? in `libs.tech/klayout/tech` along with `.lyt` and `.lyp` files
I'm not sure that's a good idea to have this long relative path in KLayout tech file, referencing another repository / folder

**Comment by dnltz** [comment]
> Hi @dnltz, is it possible to just put the `.map` file to this repo? in `libs.tech/klayout/tech` along with `.lyt` and `.lyp` files I'm not sure that's a good idea to have this long relative path in KLayout tech file, referencing another repository / folder

The path is actually used by OpenROAD to load the .map file. However, seems like no other PDK is using a .map file ... so maybe this can a workaround until a better solution for the .map file was found?

**Comment by gadfort** [comment]
@dnltz we use the layer map file as well (although we are not fully enabled for this PDK yet). https://github.com/siliconcompiler/lambdapdk and https://github.com/siliconcompiler/siliconcompiler

**Comment by sergeiandreyev** [comment]
there was a suggestion by Matthias Koefferlein (KLayout developer) last year to use the map file instead of modifying the technology `.lyt` file because the approach inside klayout is not efficient
the question is where to store / have this file

**Comment by sergeiandreyev** [comment]
I prefer to have it as part of IHP OpenPDK repository, because it's PDK specific data, we set the correct licenses, we're aware of changes and can confirm or reject them, etc.

**Comment by dnltz** [comment]
> I prefer to have it as part of IHP OpenPDK repository, because it's PDK specific data, we set the correct licenses, we're aware of changes and can confirm or reject them, etc.

alright, let me try to get this done without this OpenROAD specific path.

**Comment by dnltz** [comment]
@sergeiandreyev with some search and replace magic in ORFS, the following `.lyt` file works.

@gadfort Are you okay with an empty `lef-files` tag? Your change broke ORFS ...

**Comment by gadfort** [comment]
@dnltz yeah, an empty tag like that works for me.

**Pull request merged**
