### PR TITLE
Basic filler scripts for ihp-sg13g2 open PDK

### PR DESCRIPTION
**Pull request by KrzysztofHerman**
This PR contains basic filler scripts for the PDK.

The filling process can be run from the command line using a python script:
```
klayout -n sg13g2 -zz -r $PDK_ROOT/$PDK/libs.tech/klayout/tech/scripts/filler.py -rd output_file=./design_filled.gds design_nofill.gds   
```
It is mandatory to have a `sealring` in the design. 

In order to control metal filler densities user can modify the following scripts:

```
$PDK_ROOT/$PDK/libs.tech/klayout/tech/scripts/macros/sg13g2_filler_Metal.lym  
$PDK_ROOT/$PDK/libs.tech/klayout/tech/scripts/macros/sg13g2_filler_TopMetal.lym
``` 
where the `width`, `length` and also the `distance` between the filler cells can be altered.  Please respect the DRC rules related to the sizes and separation of the filler cells (sections `5.18` and `5.23` of the `SG13G2_Layout_Rules_os.pdf` document). 

While running `minimal DRC` in klayout one can expect ` AFil.g2`, `M1-5Fil.h`  errors related to the area outside the design, where the densities are calculated. The errors can be waived. 

Special thanks to `Daniel Schultz` for providing the scripts.

### CODE REVIEW

**Comment by dnltz** [comment]
@KrzysztofHerman just verified the metal fill scripts again. No fill outside of the sealring and not fill violations!

image

**Comment by KrzysztofHerman** [comment]
@dnltz same here:

image

**Comment by joerdsonsilva** [comment]
To submit the GDS file, do I need to fix the AFil.g2 and M1-5 Fil.h errors reported by maximal DRC?

**Comment by KrzysztofHerman** [comment]
@joerdsonsilva  I wrote in the description of this PR "While running minimal DRC in klayout one can expect  AFil.g2, M1-5Fil.h errors related to the area outside the design, where the densities are calculated. The errors can be waived." 
So please check where klayout marks this errors in you layout, it is probably mostly outside the actual design region. If this is the case you can submit it.

**Comment by sergeiandreyev** [comment]
@KrzysztofHerman, should we close this PR? as you already pushed the data

**Pull request closed without merging**
