### PR TITLE
Remove merged.lef from klayout setup

### PR DESCRIPTION
**Pull request by gadfort**
Removing reference to merged.lef which does not exist.

Fixes NA

- [X] Tests pass
- [X] Appropriate changes to README are included in PR (NA)

### CODE REVIEW

**Comment by KrzysztofHerman** [comment]
Hi @gadfort thank you for your contribution. Please read the contribution guidelines. In general we do not accept PR to the **main** branch but only to the **dev** since we follow `gitflow` branching model.  Maybe we should clarify it more. We will evaluate this change in the Klayout tech file and apply respective changes.

**Comment by gadfort** [comment]
@KrzysztofHerman I'd be happy to rebase this and set this to the `dev` branch if you would like.

**Comment by sergeiandreyev** [comment]
Hi @gadfort, yes, could you please move this PR to `dev` branch - we will approve it then

**Comment by gadfort** [comment]
@sergeiandreyev I've moved it to merge to the `dev` branch now. Thanks.

**Pull request merged**
