### PR TITLE
Fixes for standard cells library

### PR DESCRIPTION
**Pull request by b10346**
Fixes #<issue_number_goes_here>

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by KrzysztofHerman — APPROVED** [review]

**Comment by b10346** [comment]
GDS and LEF were updated: 
#167
#218
#246
#268

**Comment by b10346** [comment]
#237

**Comment by sergeiandreyev** [comment]
Hi @b10346, is it possible to rename the PR? Right now is `Dev`..

**Comment by b10346** [comment]
> Hi @b10346, is it possible to rename the PR? Right now is `Dev`..

It is not available for editing. I can not manage it.

**Comment by b10346** [comment]
Clarified. Changed.

**Pull request merged**
