### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sergeiandreyev**
Merge `dev` to `main`

### CODE REVIEW

**Comment by dnltz** [comment]
@sergeiandreyev looks like the DCO plugin is not configured correctly and doesn't run on pull requests to `dev`. Missing SOBs should be caught earlier.

**Comment by sergeiandreyev** [comment]
@dnltz , do you mean as example these 'Merge' PRs?
image
these do not have have DCO signed

**Comment by dnltz** [comment]
@sergeiandreyev no, they are fine. I mean this action (https://github.com/IHP-GmbH/IHP-Open-PDK/pull/222/checks?check_run_id=31736802611) only gets triggered when merging to the default branch. It doesn't check pull requests to `dev`, which is used as intermediate branch.


For example, this commit has no `signed-off-by`: https://github.com/IHP-GmbH/IHP-Open-PDK/pull/222/commits/00ee7623d2a02ee2926d5510927977f7bfcd3fae

**Comment by dnltz** [comment]
@sergeiandreyev everything fine! Just saw my pull request (https://github.com/IHP-GmbH/IHP-Open-PDK/pull/172) failed not with missing `signed-off-by`!

**Comment by sergeiandreyev** [comment]
ok, good!
still I don't understand for now why the merge PRs have DCO violations (see my previous comment)

**Comment by sergeiandreyev** [comment]
it seems to be limited only to the commits from Oct 18..

**Review by KrzysztofHerman — APPROVED** [review]

**Pull request merged**
