### PR TITLE
IO library fixes & improvements

### PR DESCRIPTION
**Pull request by FatsieFS**
This PR contains critical fix for the IOPadVdd cell. Previous gds should not be used anymore for new tape-outs.  
For the rest some small improvements to the generated files and docs.

### CODE REVIEW

**Comment by stafverhaegen-chipflow** [comment]
@sergeiandreyev @KrzysztofHerman  
Current CDL seems out of date. The IOPadVdd cell in the CDL still contains the ESD diodes and not the RC clamp.

**Comment by stafverhaegen-chipflow** [comment]
BTW, this thus contain fix for #101 
There is still a difference between gds I uploaded in that issue and the current gds. The former still contained a DRC with a connection with too big width on metal2.

**Comment by FatsieFS** [comment]
I only now see that Boris did still find that the bulk is connected to iovdd; so wait with merging until this is clarified.

**Comment by sergeiandreyev** [comment]
Hello Staf, let's have a sync-up on IO cells with Alexey Balashov, to be all on the same page
I guess we're going out of sync now..

**Comment by dnltz** [comment]
@FatsieFS IOPadVdd has missing slits on M2. Maximum width without slits is 30u.

**Comment by stafverhaegen-chipflow** [comment]
> @FatsieFS IOPadVdd has missing slits on M2. Maximum width without slits is 30u.

I updated patch with fixed gds. I did fix it but seems I did not properly update the gds file in the patch.
Also rebased the patch on top of latest dev branch.

**Comment by dnltz** [comment]
@stafverhaegen-chipflow just tried your new GDS and looks good to me!

image

**Comment by KrzysztofHerman** [comment]
@dnltz does it solve the problem for you? Shall we merge ?

**Comment by dnltz** [comment]
@KrzysztofHerman Slt.c is missing in the Open PDK rules but there is no area wider then 30u anymore. Should be fine.

**Comment by stafverhaegen-chipflow** [comment]
@KrzysztofHerman  
I think you can close #101 also then.  
There may still be open questions about LVS as discussed in https://github.com/IHP-GmbH/IHP-Open-PDK/pull/109#issuecomment-2110303660 but from our f2f discussion I understood Alexey would take the next steps there.

**Pull request merged**
