### PR TITLE
Nofill areas in sealring

### PR DESCRIPTION
**Pull request by dnltz**
this changes adds nofill areas to Activ, GatPoly, M1-5 and TM1-2. These areas are not super nicely drawn but at least the area around Passiv in the sealring is now marked as nofill.

Additionally, sealring includes not a prBoundary.drawing rect around the entire chip.

### CODE REVIEW

**Comment by dnltz** [comment]
@KrzysztofHerman can you please verify this is correct. I had to add those areas manually for ElemRV.

**Comment by dnltz** [comment]
This is how the sealring looks like.

image

**Comment by KrzysztofHerman** [comment]
Hi @dnltz, I have verified how the fillers are generated in the PVS and what it does it detects the `EdgeSeal.drawing` inner area and shrinks it to meet DRC. Then this layer is used as `extent_all_layers` equivalent in the current solution.  From this point of view this functionality of `nofill areas` will not be necessary,

**Comment by dnltz** [comment]
@KrzysztofHerman okay, another topic I should address when filling the chip. I assume I can close this issue?

**Comment by KrzysztofHerman** [comment]
For now I do not see anything specific to add. Let's close.

**Pull request closed without merging**
