### PR TITLE
Upstream of IO cells into IHP-Open-PDK

### PR DESCRIPTION
**Pull request by stafverhaegen-chipflow**
This is WIP pull request for a pull request to upstream the IO cells. This pull request will be updated with advancement of the IO cell library implementation.  
One of the purposes of this pull request is to encourage discussion on the structure of the added data before actually being upstreamed.

### CODE REVIEW

**Comment by stafverhaegen-chipflow** [comment]
Updated patch to only include one file for gds and spice for the io library.

**Comment by stafverhaegen-chipflow** [comment]
Updated gds: add labels on rppd resistor and antenna diodes so they are recognized by Calibre extraction deck. ESD diodes are still to be done.

**Comment by stafverhaegen-chipflow** [comment]
Last push:
- Update README.md file
- Use python notebook for generating simulation based documentation in html format
- Reduce drive strengths to '4mA', '16mA' and '30mA'
- Improve compatibility with Calibre LVS deck

**Comment by adamleehandwerger** [comment]
## Updated submission: full-chip harden with IO pad ring, bondpads, sealring

Addressing the feedback from @KrzysztofHerman — the design has been re-hardened using LibreLane Chip flow (IHP SG13G2, v3.0.4) with a complete pad ring.

**GDS download:** https://github.com/adamleehandwerger/ihp-sg13g2-svm/releases/tag/v2.0-chip-harden

### Die specification
| Parameter | Value |
|-----------|-------|
| Die area | 2400 × 2400 µm |
| Core area | 1670 × 1670 µm |
| IO pad cells | 54 signal + 12 power (sg13g2_IOPadIn / sg13g2_IOPadOut30mA) |
| Bondpads | sg13g2_ip__bondpad_70x70 (70 × 70 µm, all signal pads) |
| Sealring | Added by LibreLane KLayout.Sealring |
| Metal fill | All layers via KLayout.Filler (Activ, Metal1–5, TopMetal1/2) |
| Hardened macro | svm_compute_core 1400 × 1400 µm @ [400, 400] |

### Signoff
- **KLayout DRC:** 23 Metal2 density violations (M2.j: 34.10% vs 35.0% minimum). The shortfall is caused by the 1400×1400 µm hardened macro blocking fill insertion in the core area. All other density layers pass. Happy to discuss if a waiver is possible or if there is a preferred method to add Metal2 fill inside the macro footprint.
- **Magic DRC:** Skipped (exceeds available compute time on full-chip geometry; can be provided on request).
- **Timing:** WNS positive at 40 MHz for core logic; IO pad nets show slew/cap warnings (pad cells treated as black boxes).

**Design:** 5-class SVM cardiac arrhythmia classifier, ECE410 ASIC design, Portland State University.
**Contact:** Adam Handwerger, handwerg@pdx.edu

**Pull request merged**
